stages:
  - lint
  - migrate
  - test

variables:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  REDIS_URL: redis://redis:6379
lint:
  image: golangci/golangci-lint:latest
  stage: lint

  script:
    - go mod download
    - make lint

migrate:
  image: migrate/migrate:v4.17.0
  stage: migrate
  services:
    - postgres:14
  variables:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  script:
    - echo "$DATABASE_URL"
    - migrate -path db/migrations -database "$DATABASE_URL" up

test:
  image: golang:1.26
  stage: test

  services:
    - name: postgres:14
      alias: postgres
      variables:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    - name: redis:7-alpine
      alias: redis

  script:
    - go mod download
    - make tests
