services:
  application:
    image: ghcr.io/mom4uk/weather-viewer:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    restart: always

  redis:
    restart: always