services:
  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: go run ./cmd/main.go

  postgres:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres