name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Run lint
        run: golangci-lint run

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"
          cache: true

      - name: Install migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -U postgres; do
            sleep 1
          done

      - name: Run migrations
        run: |
          migrate -path=db/migrations \
            -database "$DATABASE_URL" \
            -verbose up

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID }}
          files: coverage.out